name: Update source data

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-source-data:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.7'
        architecture: 'x64'
    - name: Cache Pip
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Update Datasets
      run: python scripts/update.py
    - name: Update County Interventions
      run: python scripts/update-interventions-naco.py
# TODO: create PR from results
